### ISSUE TITLE
Only works with touch, not mouse

### ISSUE THREAD

**Issue by TwoTau** [gcliau100/Fling-the-Ball#1]

**Comment by whalephisher** [comment]
can you make it so that you can use the mouse also

**Comment by TwoTau** [comment]
Yeah, finished. I added [event listeners](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) for mouse events.

However, you can swipe faster than you can move your mouse.
So, the ball is usually slower when using the mouse than when using touch.

**Comment by whalephisher** [comment]
awesome!
